export const ClientRegister_INITIAL_STATE: ClientRegister = {
  name: '',
  email: '',
  password: '',
  confirmPassword: '',
  role: 'client',
  phone: '',
  address: '',
  address2: '',
  city: '',
  region: '',
  postCode: '',
  country: '',
  company: '',
  CIF: '',
};

export const dataValidation_INITIAL_VALUE = {
  name: false,
  email: false,
  password: false,
  confirmPassword: false,
  phone: false,
  address: false,
  address2: false,
  city: false,
  region: false,
  postCode: false,
  country: false,
  company: false,
  CIF: false,
  allfields: false,
};
