export const clientFormTextInputs: FormTextInputs[] = [
  {
    name: 'name',
    autocomplete: 'name',
    label: 'Nombre',
    type: 'text',
    placeholder: 'Nombre',
    errorName: 'name',
    error: 'El nombre debe tener al menos dos caracteres',
  },

  {
    name: 'email',
    autocomplete: 'email',
    label: 'Email',
    type: 'email',
    placeholder: 'Email',
    errorName: 'email',
    error: 'El email no es correcto',
  },
  {
    name: 'phone',
    autocomplete: 'tel',
    label: 'Teléfono',
    type: 'phone',
    placeholder: '999 99 99',
    errorName: 'phone',
    error: 'El teléfono no es correcto',
  },
  {
    name: 'address',
    autocomplete: 'address-line1',
    label: 'Dirección',
    type: 'address',
    placeholder: 'nombre de la calle, número, piso, puerta',
    errorName: '',
    error: '',
  },
  {
    name: 'address2',
    autocomplete: 'address-line2',
    label: '',
    type: 'address2',
    placeholder: '',
    errorName: 'address',
    error: 'La dirección no es correcta',
  },
  {
    name: 'city',
    autocomplete: 'address-line3',
    label: 'Población',
    type: 'city',
    placeholder: 'Madrid',
    errorName: 'city',
    error: 'El teléfono no es correcto',
  },
  {
    name: 'region',
    autocomplete: 'off',
    label: 'Comunidad autonoma',
    type: 'region',
    placeholder: 'Comunidad autonoma',
    errorName: 'region',
    error: 'La región no es correcta',
    list: [
      'Andalucía',
      'Aragón',
      'Asturias',
      'Comunidad Valenciane',
      'Islas Baleares',
      'Canarias',
      'Cantabria',
      'Castilla-La Mancha',
      'Castilla y León',
      'Cataluña',
      'Comunidad Valenciana',
      'Extremadura',
      'Galicia',
      'Comunidad de Madrid',
      'Región de Murcia',
      'Comunidad Foral de Navarra',
      'País Vasco',
      'La Rioja',
      'Ceuta',
      'Melilla',
    ],
  },
  {
    name: 'postCode',
    autocomplete: 'postal-code',
    label: 'Código postal',
    type: 'postCode',
    placeholder: 'Código postal',
    errorName: 'postCode',

    error: 'El código postal no es correcto',
  },
  {
    name: 'country',
    autocomplete: 'country-name',
    label: 'País',
    type: 'country',
    placeholder: 'País',
    errorName: 'country',

    error: 'Este campo es obligatorio',
  },
  {
    name: 'company',
    autocomplete: 'off',
    label: 'Nombre de la empresa',
    type: 'company',
    placeholder: 'Mi empresa',
    errorName: 'company',
    error: 'Este campo es obligatorio',
  },
  {
    name: 'CIF',
    autocomplete: 'off',
    label: 'Número Cif',
    type: 'CIF',
    placeholder: 'Mi empresa',
    errorName: 'CIF',
    error: 'El CIF no es correcto',
  },
  {
    name: 'password',
    autocomplete: 'off',
    label: 'Password',
    type: 'Password',
    placeholder: 'Password',
    errorName: 'password',
    error:
      'La contraseña debe tener al menos ocho caracteres, un caracter especial, un número y una mayúscula',
  },
  {
    name: 'confirmPassword',
    autocomplete: 'off',
    label: 'Confirm Password',
    type: 'confirmPassword',
    placeholder: 'confirmPassword',
    errorName: 'confirmPassword',
    error: 'Las contraseñas no coinciden',
  },
  {
    name: 'service1',
    label: 'Sercicio 1',
    type: 'checkbox',
    placeholder: '',
    errorName: '',
    error: '',
  },
  {
    name: 'service2',
    label: 'Sercicio 2',
    type: 'checkbox',
    placeholder: '',
    errorName: '',
    error: '',
  },
  {
    name: 'service3',
    label: 'Sercicio 3',
    type: 'checkbox',
    placeholder: '',
    errorName: '',
    error: '',
  },
  {
    name: 'service4',
    label: 'Sercicio 4',
    type: 'checkbox',
    placeholder: '',
    errorName: '',
    error: '',
  },
  {
    name: 'service5',
    label: 'Sercicio 5',
    type: 'checkbox',
    placeholder: '',
    errorName: '',
    error: '',
  },
  {
    name: 'service6',
    label: 'Sercicio 6',
    type: 'checkbox',
    placeholder: '',
    errorName: '',
    error: '',
  },
  {
    name: 'service7',
    label: 'Sercicio 7',
    type: 'checkbox',
    placeholder: '',
    errorName: '',
    error: '',
  },
  {
    name: 'service8',
    label: 'Sercicio 8',
    type: 'checkbox',
    placeholder: '',
    errorName: '',
    error: '',
  },
  {
    name: 'service9',
    label: 'Sercicio 9',
    type: 'checkbox',
    placeholder: '',
    errorName: '',
    error: '',
  },
  {
    name: 'service10',
    label: 'Sercicio 10',
    type: 'checkbox',
    placeholder: '',
    errorName: '',
    error: '',
  },
];
